using System.Text.Json;
using System.Text.Json.Serialization;
using System.Web;

namespace Assignment_3
{
    public class SentimentAnalysis
    {
        [JsonPropertyName("label")]

        public string Label { get; set; }

        [JsonPropertyName("score")]

        public float Score { get; set; }
        private const int MaxInputLength = 512;


        public static async Task<List<string>> SearchRedditAsync(string searchQuery)

        {

            List<string> returnList = new List<string>();

            using (HttpClient client = new HttpClient())

            {

                client.DefaultRequestHeaders.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");

                string json = await client.GetStringAsync("https://api.pullpush.io/reddit/search/comment/?size=25&q=" + HttpUtility.UrlEncode(searchQuery)); JsonDocument doc = JsonDocument.Parse(json);

                // Check if "data" array exists

                if (doc.RootElement.TryGetProperty("data", out JsonElement dataArray))

                {

                    foreach (JsonElement comment in dataArray.EnumerateArray())

                    {

                        // Check if "body" exists

                        if (comment.TryGetProperty("body", out JsonElement bodyElement))

                        {

                            string textToAdd = bodyElement.GetString();

                            if (!string.IsNullOrEmpty(textToAdd))

                            {

                                textToAdd = TruncateToMaxLength(textToAdd, MaxInputLength);

                                returnList.Add(textToAdd);

                            }
                        }
                    }
                }
            }
            return returnList;
        }
    
    //code generated by chatgpt below

        // Truncates a string to a maximum length, safely, without splitting surrogate pairs/emoji.
        // This is the method your existing code is calling.
        private static string TruncateToMaxLength(string input, int maxLength)
        {
            if (string.IsNullOrEmpty(input) || maxLength <= 0)
                return string.Empty;

            if (input.Length <= maxLength)
                return input;

            // Delegate the actual truncation to a helper.
            return TruncateAtTextElementBoundary(input, maxLength);
        }

        // Helper that TruncateToMaxLength calls.
        // It truncates on a "text element" boundary (safer for emoji / combining chars).
        private static string TruncateAtTextElementBoundary(string input, int maxLength)
        {
            // If maxLength cuts through a surrogate pair, back up by one char.
            // This avoids producing invalid UTF-16.
            if (maxLength > 0 &&
                maxLength < input.Length &&
                char.IsHighSurrogate(input[maxLength - 1]) &&
                char.IsLowSurrogate(input[maxLength]))
            {
                maxLength--;
            }

            return input.Substring(0, maxLength);
        }
    }
    }
